### ISSUE TITLE
Sort home page repositories by stars and cap number of repositories shown

### ISSUE THREAD

**Issue by ffeltrinelli** [ExpediaGroup/expediagroup.github.io#11]
Regarding the repositories we show in the home page, this issue is to:

1. sort repositories by stars (descending); to do this, fetch also the number of stars with GitHub API
2. show only the first N repositories from this sorted list (N should be configurable); given we have rows of 3 elements, we could configure N=6 or 9.

**Comment by ffeltrinelli** [comment]
@massdosage @nikos912000 thoughts on this proposal of mine?

**Comment by nikos912000** [comment]
Tbh the list is small enough so we can hardcode the repos? This has the advantage that we fully control the list and we can pick projects from different domains.

If we want something more dynamic we could sort based on a metric.
But most metrics including the number of stars are prone to issues, such as the cold-start one; it takes a lot of time for a new project to make it to the list.

**Comment by massdosage** [comment]
I think I'm fine with having the list hard coded for now, we can then manually add new projects for a while to avoid the "cold start" issue and leave them there if they catch on, otherwise replace them with others. This is a bit like how we manage the "pinned" repositories on GH at the moment. If we did want to automate this, then maybe we could do something like "first 6 projects are ordered by stars and next 3 are the newest created repos not in the first 6" if that makes sense?

**Comment by ffeltrinelli** [comment]
Thanks both! I agree on keeping it as simple as possible.

> first 6 projects are ordered by stars and next 3 are the newest created repos not in the first 6

this seems a good tradeoff!

I realized what I really wanted to highlight is the distinction between "featured" repositories, which is the subset of repos we show in the home page, and "all" repositories, which we are thinking to show in a dedicated page. To achieve this distinction, I was thinking at some kind of automation that would select the subset for the home page. But I think it's premature now, I'll move this issue to a dedicated "Repositories Page" project. :-)

**Comment by ffeltrinelli** [comment]
I'm closing this issue as we seem to be fine with an hardcoded list of featured repositories, for the time being.
